apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name
  labels:
    name: name
spec:
  replicas:
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
      - name: name
        image: sudhakr/name
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /resources/names/1
            port: 8082
          initialDelaySeconds: 50
          periodSeconds: 5
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.default
