apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
