apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: greeting-90-10
spec:
  destination:
    name: greeting
  route:
  - labels:
      greeting: hello
    weight: 90
  - labels:
      greeting: howdy
    weight: 10
