apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: greeting-delay-10
spec:
  destination:
    name: greeting
  route:
  - labels:
      greeting: hello
#introduce a 5 second delay in 10% of the requests
  httpFault:
    delay:
      percent: 10
      fixedDelay: 5s
